### ISSUE TITLE
undefined method `bytesize` for Hash

### ISSUE THREAD

**Issue by dpogue** [google/signet#69]
This works with an older (pre-0.7.0) version of signet. It seems like this possibly broke when hurley support was added.

```
NoMethodError: undefined method `bytesize' for #<Hash:0x007fd8c5dd31a0>
/project/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
/project/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
/project/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
/project/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
/project/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
/project/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/project/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/project/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
/project/gems/signet-0.7.1/lib/signet/oauth_2/client.rb:960:in `fetch_access_token'
/project/gems/signet-0.7.1/lib/signet/oauth_2/client.rb:997:in `fetch_access_token!'
/project/lib/tasks/fetch.rake:32:in `get_access_token'
/project/lib/tasks/fetch.rake:148:in `block (2 levels) in <top (required)>'
```

My code in fetch.rake looks like this:
```ruby
    client = Google::APIClient.new
    auth = client.authorization
    auth.client_id = CLIENT_ID
    auth.client_secret = CLIENT_SECRET
    auth.scope = 'https://www.googleapis.com/auth/drive https://spreadsheets.google.com/feeds'
    auth.redirect_uri = "urn:ietf:wg:oauth:2.0:oob"

    print("1. Open this page:\n%s\n\n" % auth.authorization_uri)
    print("2. Enter the authorization code shown in the page: ")
    auth.code = $stdin.gets.chomp
    auth.fetch_access_token!(:connection => client.connection)
    access_token = auth.access_token

    return access_token
```

**Comment by sqrrrl** [comment]
D'oh! Looks like the older versions of api client omit the form encoding middleware. Just pushed 0.7.2 which should fix the issue (doesn't assume the middleware exists for faraday)
